### PR TITLE
Added WKWebViewConfiguration setting

### PR DESCRIPTION
**Pull request by SNQ-2001**
# Usage
```swift
import SwiftUI
import WebViewKit
import WebKit

struct ContentView: View {
    @State var isPresentedWebView: Bool = false
    private let url = "https://gs.statcounter.com/detect"
    var body: some View {
        VStack {
            Button {
                isPresentedWebView = true
            } label: {
                Text("Show WebView")
            }
        }
        .sheet(isPresented: $isPresentedWebView) {
            WebView(url: URL(string: url), configuration: configuration) { webView in
                webView.customUserAgent = "foo bar"
            }
        }
    }
    // Example of WKWebViewConfiguration
    var configuration: WKWebViewConfiguration {
        let disableSelectionScriptString = "document.documentElement.style.webkitUserSelect='none';"
        let disableCalloutScriptString = "document.documentElement.style.webkitTouchCallout='none';"

        let disableSelectionScript = WKUserScript(source: disableSelectionScriptString, injectionTime: .atDocumentEnd, forMainFrameOnly: true)
        let disableCalloutScript = WKUserScript(source: disableCalloutScriptString, injectionTime: .atDocumentEnd, forMainFrameOnly: true)

        let userContentController = WKUserContentController()
        userContentController.addUserScript(disableSelectionScript)
        userContentController.addUserScript(disableCalloutScript)

        let configuration = WKWebViewConfiguration()
        configuration.userContentController = userContentController
        configuration.ignoresViewportScaleLimits = false

        return configuration
    }
}
```

### CODE REVIEW

**Comment by danielsaidi** [comment]
Hi @SNQ-2001 

Sorry for the slow reply. Can you please describe in more detail what this does?

**Comment by SNQ-2001** [comment]
@danielsaidi 

Thank you for your confirmation.

WKWebView has a feature called `WKWebViewConfiguration `.
The current implementation could not configure this, so I added it.

`WKWebViewConfiguration` is a configuration class that is loaded at WebView initialization.

Using `WKWebViewConfiguration`, you can set many options.

The PR sample code executes the following two JavaScripts at initialization.

- Prohibition of text selection
- Prohibition of menu display by long-press

[WKWebViewConfiguration]
https://developer.apple.com/documentation/webkit/wkwebviewconfiguration

**Review by danielsaidi — APPROVED** [review]

**Comment by danielsaidi** [comment]
Hi @SNQ-2001 

Sorry for this insanely slow review and thank you for providing this addition!

**Comment by danielsaidi** [comment]
I'm releasing this as a `0.2.2` 👍

**Pull request merged**
